name: Generate Snake Animation ğŸ

on:
  schedule:
    - cron: "0 0 * * *" # ë§¤ì¼ ìì •ì— ì‹¤í–‰
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate the snake animation
        uses: Platane/snk@master
        with:
          github_user_name: YJ-Kkang
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push the animation
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Action
          author_email: actions@github.com
          message: "Generated snake animation"
          add: "dist/*.svg"
